name: Auto Restart Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Clone
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Dependencies Install
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        run: python restart.py
